apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    environment: dev
patches:
- path: microservice-patch.yaml
- path: postgres-patch.yaml
- path: ingress-patch.yaml
