kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
        - containerPort: 30000
          hostPort: 80
  - role: worker  # Non-GPU node
  - role: worker  # GPU node
    labels:
      gpu: "true"
